### ISSUE TITLE
logo proposal

### ISSUE THREAD

**Issue by Batarian711** [learn-anything/curated-lists#2]
I want to design a custom logo for you. For the readme file. What do you say?

**Comment by nikivdev** [comment]
Sounds good. Send what you have in mind here and we can discuss it. 🙂

**Comment by Batarian711** [comment]
I have designed a logo that represents lists and aims to be preferred. What dou you think?

![untitled-1](https://user-images.githubusercontent.com/41051393/47696341-07e70180-dc0f-11e8-9dac-6e69919547cb.jpg)

**Comment by nikivdev** [comment]
We don't need a logo for the lists. Thanks though ♥️
